# fly.toml file generated for rails-functions on 2023-04-14T00:04:49+08:00

app = "rails-functions"
kill_timeout = 0
primary_region = "nrt"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
